name: Deploy to OCI VM

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    name: Pull and Run Image on OCI
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into VM and pull/run container
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            echo "${{ secrets.GHCR_PAT }}" | sudo podman login ghcr.io -u ${{ github.actor }} --password-stdin
      
            IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
            sudo podman pull $IMAGE_NAME  

            echo "Checking if Podman Network exists..."
            if ! sudo podman network ls | grep -q my_custom_network; then
              echo "Creating Podman Network 'my_custom_network'"
              sudo podman network create my_custom_network
            else
              echo "Network 'my_custom_network' already exists"
            fi

            echo "Calling Podman Stop"
            sudo podman stop tavily-mcp 2>/dev/null || true

            echo "Calling Podman Rm"
            sudo podman rm tavily-mcp 2>/dev/null || true

            echo "Calling Podman Run"
            sudo podman run -d \
              --name tavily-mcp \
              --network my_custom_network \
              --restart=always \
              --log-driver=k8s-file \
              --log-opt path=/var/log/tavily-mcp.log \
              -e TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }} \
              $IMAGE_NAME

            echo "✅  tavily-mcp container deployed successfully"

          EOF
